/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package sbild.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EmpltopCnt service. Represents a row in the &quot;GB_EmpltopCnt&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>sbild.model.impl.EmpltopCntModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>sbild.model.impl.EmpltopCntImpl</code>.
 * </p>
 *
 * @author liferay
 * @see EmpltopCnt
 * @generated
 */
@ProviderType
public interface EmpltopCntModel extends BaseModel<EmpltopCnt> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a empltop cnt model instance should use the {@link EmpltopCnt} interface instead.
	 */

	/**
	 * Returns the primary key of this empltop cnt.
	 *
	 * @return the primary key of this empltop cnt
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this empltop cnt.
	 *
	 * @param primaryKey the primary key of this empltop cnt
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the position of this empltop cnt.
	 *
	 * @return the position of this empltop cnt
	 */
	@AutoEscape
	public String getPosition();

	/**
	 * Sets the position of this empltop cnt.
	 *
	 * @param position the position of this empltop cnt
	 */
	public void setPosition(String position);

	/**
	 * Returns the lastname of this empltop cnt.
	 *
	 * @return the lastname of this empltop cnt
	 */
	@AutoEscape
	public String getLastname();

	/**
	 * Sets the lastname of this empltop cnt.
	 *
	 * @param lastname the lastname of this empltop cnt
	 */
	public void setLastname(String lastname);

	/**
	 * Returns the count of this empltop cnt.
	 *
	 * @return the count of this empltop cnt
	 */
	public int getCount();

	/**
	 * Sets the count of this empltop cnt.
	 *
	 * @param count the count of this empltop cnt
	 */
	public void setCount(int count);

}