/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package sbild.model;

import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Purchase service. Represents a row in the &quot;GB_Purchase&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>sbild.model.impl.PurchaseModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>sbild.model.impl.PurchaseImpl</code>.
 * </p>
 *
 * @author liferay
 * @see Purchase
 * @generated
 */
@ProviderType
public interface PurchaseModel extends BaseModel<Purchase> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a purchase model instance should use the {@link Purchase} interface instead.
	 */

	/**
	 * Returns the primary key of this purchase.
	 *
	 * @return the primary key of this purchase
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this purchase.
	 *
	 * @param primaryKey the primary key of this purchase
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the purch ID of this purchase.
	 *
	 * @return the purch ID of this purchase
	 */
	public long getPurchId();

	/**
	 * Sets the purch ID of this purchase.
	 *
	 * @param purchId the purch ID of this purchase
	 */
	public void setPurchId(long purchId);

	/**
	 * Returns the electr ID of this purchase.
	 *
	 * @return the electr ID of this purchase
	 */
	public long getElectrId();

	/**
	 * Sets the electr ID of this purchase.
	 *
	 * @param electrId the electr ID of this purchase
	 */
	public void setElectrId(long electrId);

	/**
	 * Returns the empl ID of this purchase.
	 *
	 * @return the empl ID of this purchase
	 */
	public long getEmplId();

	/**
	 * Sets the empl ID of this purchase.
	 *
	 * @param emplId the empl ID of this purchase
	 */
	public void setEmplId(long emplId);

	/**
	 * Returns the purch date of this purchase.
	 *
	 * @return the purch date of this purchase
	 */
	public Date getPurchDate();

	/**
	 * Sets the purch date of this purchase.
	 *
	 * @param purchDate the purch date of this purchase
	 */
	public void setPurchDate(Date purchDate);

	/**
	 * Returns the purchtype ID of this purchase.
	 *
	 * @return the purchtype ID of this purchase
	 */
	public long getPurchtypeId();

	/**
	 * Sets the purchtype ID of this purchase.
	 *
	 * @param purchtypeId the purchtype ID of this purchase
	 */
	public void setPurchtypeId(long purchtypeId);

}